name: resume_builder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true

  # Used for iOS and Android legacy icons (WITH background)
  image_path: assets/icon/icon.png

  # Android adaptive icon (foreground MUST be transparent)
  adaptive_icon_foreground: assets/icon/icon_foreground.png
  adaptive_icon_background: "#FFFFFF"
